version: 2.1

orbs:
  maven: circleci/maven@1.3.0

executors:
  j8:
    docker:
      - image: cimg/openjdk:8.0

jobs:
  build:
    executor: j8
    steps:
      - checkout
      - maven/with_cache:
          maven_command:
            echo SKIP
          steps:
            - run: java -XX:+PrintFlagsFinal -version
            - run: mvn --version
            - run: mvn verify -Dplay.seleniumSkip -Dplay.dependenciesSkipJars -Pautodeps,dist,play13,with-external-modules --update-snapshots -e --settings .travis.settings.xml
      - maven/process_test_results
workflows:
  build:
    when:
      not:
        equal: [ tools, << pipeline.git.branch >> ]
    jobs:
      - build
